In [21]:
import pandas as pd
import re
import string
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [22]:
import pandas as pd
df = pd.read_csv("../dataset/master.csv")
text_column = "review"

In [23]:
def case_folding(text):
    return str(text).lower()

# Contoh
text = "Saya Belajar NLP"
print(case_folding(text))
# Output: saya belajar nlp

saya belajar nlp

In [24]:
def remove_url(text):
    return re.sub(r"http\S+|www\S+", "", text)

# Contoh
text = "Kunjungi https://example.com sekarang"
print(remove_url(text))
# Output: Kunjungi  sekarang

Kunjungi  sekarang

In [25]:
def remove_mention(text):
    return re.sub(r"@\w+", "", text)

# Contoh
text = "@user1 produk ini bagus"
print(remove_mention(text))

 produk ini bagus

In [26]:
import re
import pandas as pd

def remove_hashtag(text):
    if pd.isna(text):
        return text
    return re.sub(r"#\w+", "", text)

df["review_bersih"] = df["review"].apply(remove_hashtag)

display(df[["review", "review_bersih"]].head())

,review,review_bersih
0,Kualitas ok\nPelayanan ok,Kualitas ok\nPelayanan ok
1,"kemasan bagus,pengiriman dan respon oke semoga...","kemasan bagus,pengiriman dan respon oke semoga..."
2,Ok paket sampaii tks gan,Ok paket sampaii tks gan
3,"Produk sangat bagus, seller top banget","Produk sangat bagus, seller top banget"
4,.................................................,.................................................

In [27]:
mask = df["review"].str.contains(r"#\w+", na=False)

display(df.loc[mask, ["review", "review_bersih"]].head(10))

,review,review_bersih
196,"TOKO PENIPU, BARANG GA DIKIRIM&#34;, JANJI R...","TOKO PENIPU, BARANG GA DIKIRIM&;, JANJI REFU..."
211,"buku aman sampai tujuan, bener&#34; rapi packi...","buku aman sampai tujuan, bener&; rapi packingn..."
223,D aku usia 46 tidk cocok d pakai jdi bengkak k...,D aku usia 46 tidk cocok d pakai jdi bengkak k...
236,ada cacat rusak bolong bagian dada (dijatuhin ...,ada cacat rusak bolong bagian dada (dijatuhin ...
400,"Oke lah, cm debit yg keluar menurut sy kurang ...","Oke lah, cm debit yg keluar menurut sy kurang ..."
450,"untuk yg grey, aromanya semakin lama semakin m...","untuk yg grey, aromanya semakin lama semakin m..."
452,Produk yg dirandai &#34;dilayani tokopedia&#34...,Produk yg dirandai &;dilayani tokopedia&; seka...
477,Mantap bosku!! cuman untuk packingnya next tim...,Mantap bosku!! cuman untuk packingnya next tim...
1056,Terima kasih.. sampe di note JNE nya &#34;past...,Terima kasih.. sampe di note JNE nya &;pastika...
1120,Bahan: Bagus\nKarakteristik: okelhh\nDurabilit...,Bahan: Bagus\nKarakteristik: okelhh\nDurabilit...

In [28]:
def remove_number(text):
    return re.sub(r"\d+", "", text)

In [29]:
def remove_punctuation(text):
    return text.translate(
        str.maketrans("", "", string.punctuation)
    )

In [30]:
def clean_whitespace(text):
    return re.sub(r"\s+", " ", text).strip()

In [31]:
def clean_text(text):
    text = str(text)
    text = text.lower()           # case folding
    text = remove_url(text)       # hapus URL
    text = remove_mention(text)   # hapus mention
    text = remove_hashtag(text)   # hapus hashtag
    text = remove_number(text)    # hapus angka
    text = remove_punctuation(text)  # hapus punctuation
    text = clean_whitespace(text) # bersihkan whitespace
    return text

In [32]:
import re
import string
import pandas as pd

text_column = "review"

def clean_text(text):
    if pd.isna(text):
        return text

    text = re.sub(r"#\w+", "", text)  # Hapus hashtag beserta katanya
    text = text.translate(str.maketrans("", "", string.punctuation))
    text = re.sub(r"\s+", " ", text).strip()  # Rapikan spasi
    return text

df["clean_text"] = df[text_column].apply(clean_text)

display(df[[text_column, "clean_text"]].head(10))

,review,clean_text
0,Kualitas ok\nPelayanan ok,Kualitas ok Pelayanan ok
1,"kemasan bagus,pengiriman dan respon oke semoga...",kemasan baguspengiriman dan respon oke semoga ...
2,Ok paket sampaii tks gan,Ok paket sampaii tks gan
3,"Produk sangat bagus, seller top banget",Produk sangat bagus seller top banget
4,.................................................,
5,"kualitas barang jelek, lubang baud jebol tidak...",kualitas barang jelek lubang baud jebol tidak ...
6,"Ini emang gada dus nya atau gmna ya,\nPackagin...",Ini emang gada dus nya atau gmna ya Packaging ...
7,"cekernya bersih², bungkus nya rapi 👍👍👍",cekernya bersih² bungkus nya rapi 👍👍👍
8,mantap mantap mantap mantap mantap mantap,mantap mantap mantap mantap mantap mantap
9,"Bagus Banget, Saya akan beli lagi satu lagi",Bagus Banget Saya akan beli lagi satu lagi

In [33]:
df["clean_text"] = df[text_column].apply(clean_text)

df[[text_column, "clean_text"]].head(10)

,review,clean_text
0,Kualitas ok\nPelayanan ok,Kualitas ok Pelayanan ok
1,"kemasan bagus,pengiriman dan respon oke semoga...",kemasan baguspengiriman dan respon oke semoga ...
2,Ok paket sampaii tks gan,Ok paket sampaii tks gan
3,"Produk sangat bagus, seller top banget",Produk sangat bagus seller top banget
4,.................................................,
5,"kualitas barang jelek, lubang baud jebol tidak...",kualitas barang jelek lubang baud jebol tidak ...
6,"Ini emang gada dus nya atau gmna ya,\nPackagin...",Ini emang gada dus nya atau gmna ya Packaging ...
7,"cekernya bersih², bungkus nya rapi 👍👍👍",cekernya bersih² bungkus nya rapi 👍👍👍
8,mantap mantap mantap mantap mantap mantap,mantap mantap mantap mantap mantap mantap
9,"Bagus Banget, Saya akan beli lagi satu lagi",Bagus Banget Saya akan beli lagi satu lagi

In [34]:
stop_words = set(stopwords.words("indonesian"))

def remove_stopwords(tokens):
    return [
        token for token in tokens
        if token not in stop_words
    ]

# Contoh
tokens = ["saya", "sedang", "belajar", "nlp", "yang", "menarik"]
print(remove_stopwords(tokens))

['belajar', 'nlp', 'menarik']

In [35]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

# Contoh
text = "Mahasiswa sedang mempelajari pemrograman."
print(stemmer.stem(text))

mahasiswa sedang ajar pemrograman

In [36]:
import re

def remove_url(text):
    return re.sub(r"https?://\S+|www\.\S+", "", str(text))

In [37]:
import re

def remove_url(text):
    return re.sub(r"https?://\S+|www\.\S+", "", str(text))

def remove_mention(text):
    return re.sub(r"@\w+", "", str(text))

In [38]:

def preprocessing_pipeline(text):
    # 1. Cleaning
    text = clean_text(text)

    # 2. Tokenization
    tokens = word_tokenize(text)

    # 3. Stopword removal
    tokens = remove_stopwords(tokens)

    # 4. Stemming
    tokens = stem_tokens(tokens)

    return tokens

# Menerapkan ke dataset
df["processed_tokens"] = df[text_column].apply(preprocessing_pipeline)

In [39]:
df["processed_text"] = df["processed_tokens"].apply(
    lambda tokens: " ".join(tokens)
)

In [40]:
for i in range(5):
    print("RAW:")
    print(df.iloc[i][text_column])

    print("\nPROCESSED:")
    print(df.iloc[i]["processed_text"])

    print("=" * 80)

RAW:
Kualitas ok
Pelayanan ok

PROCESSED:
kualitas ok layan ok
================================================================================
RAW:
kemasan bagus,pengiriman dan respon oke semoga hasilnya mantap

PROCESSED:
kemas baguspengiriman respon oke moga hasil mantap
================================================================================
RAW:
Ok paket sampaii tks gan

PROCESSED:
ok paket sampai tks gan
================================================================================
RAW:
Produk sangat bagus, seller top banget

PROCESSED:
produk bagus seller top banget
================================================================================
RAW:
..........................................................................................

PROCESSED:

================================================================================

In [41]:
output_columns = [text_column, "clean_text", "processed_text"]

df[output_columns].to_csv(
    "../dataset/dataset_preprocessed.csv",
    index=False
)

print("Dataset berhasil disimpan.")

Dataset berhasil disimpan.

In [42]:
import re
import pandas as pd
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# Baca dataset (sesuaikan path jika lokasi notebook berbeda)
df = pd.read_csv("../dataset/master.csv")
text_column = "review"

# Siapkan stemmer dan daftar stopword Bahasa Indonesia
stemmer = StemmerFactory().create_stemmer()
stopwords = set(StopWordRemoverFactory().get_stop_words())

# Ambil 20 ulasan yang tidak kosong
raw_texts = df[text_column].dropna().astype(str).head(20)

if len(raw_texts) < 20:
    raise ValueError(f"Dataset hanya memiliki {len(raw_texts)} ulasan yang tidak kosong.")

hasil = []

for raw_text in raw_texts:
    # Lowercase
    lowercase = raw_text.lower()

    # Cleaning: hapus URL, mention, hashtag beserta katanya, tanda baca, dan spasi berlebih
    cleaned = re.sub(r"https?://\S+|www\.\S+", " ", lowercase)
    cleaned = re.sub(r"@\w+|#\w+", " ", cleaned)
    cleaned = re.sub(r"[^\w\s]", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned).strip()

    # Tokenisasi
    tokens = re.findall(r"\b\w+\b", cleaned)

    # Hapus stopword
    tokens_without_stopwords = [
        token for token in tokens if token not in stopwords
    ]

    # Stemming
    stemmed_text = stemmer.stem(" ".join(tokens_without_stopwords))

    hasil.append({
        "Raw Text": raw_text,
        "Setelah Lowercase": lowercase,
        "Setelah Cleaning": cleaned,
        "Setelah Tokenisasi": tokens,
        "Setelah Stopword": tokens_without_stopwords,
        "Setelah Stemming": stemmed_text,
    })

tabel_eksperimen = pd.DataFrame(hasil)
display(tabel_eksperimen)

,Raw Text,Setelah Lowercase,Setelah Cleaning,Setelah Tokenisasi,Setelah Stopword,Setelah Stemming
0,Kualitas ok\nPelayanan ok,kualitas ok\npelayanan ok,kualitas ok pelayanan ok,"[kualitas, ok, pelayanan, ok]","[kualitas, pelayanan]",kualitas layan
1,"kemasan bagus,pengiriman dan respon oke semoga...","kemasan bagus,pengiriman dan respon oke semoga...",kemasan bagus pengiriman dan respon oke semoga...,"[kemasan, bagus, pengiriman, dan, respon, oke,...","[kemasan, bagus, pengiriman, respon, oke, semo...",kemas bagus kirim respon oke moga hasil mantap
2,Ok paket sampaii tks gan,ok paket sampaii tks gan,ok paket sampaii tks gan,"[ok, paket, sampaii, tks, gan]","[paket, sampaii, tks, gan]",paket sampai tks gan
3,"Produk sangat bagus, seller top banget","produk sangat bagus, seller top banget",produk sangat bagus seller top banget,"[produk, sangat, bagus, seller, top, banget]","[produk, sangat, bagus, seller, top, banget]",produk sangat bagus seller top banget
4,.................................................,.................................................,,[],[],
5,"kualitas barang jelek, lubang baud jebol tidak...","kualitas barang jelek, lubang baud jebol tidak...",kualitas barang jelek lubang baud jebol tidak ...,"[kualitas, barang, jelek, lubang, baud, jebol,...","[kualitas, barang, jelek, lubang, baud, jebol,...",kualitas barang jelek lubang baud jebol kuat t...
6,"Ini emang gada dus nya atau gmna ya,\nPackagin...","ini emang gada dus nya atau gmna ya,\npackagin...",ini emang gada dus nya atau gmna ya packaging ...,"[ini, emang, gada, dus, nya, atau, gmna, ya, p...","[emang, gada, dus, nya, gmna, packaging, sih, ...",emang gada dus nya gmna packaging sih pake kar...
7,"cekernya bersih², bungkus nya rapi 👍👍👍","cekernya bersih², bungkus nya rapi 👍👍👍",cekernya bersih² bungkus nya rapi,"[cekernya, bersih², bungkus, nya, rapi]","[cekernya, bersih², bungkus, nya, rapi]",ceker bersih bungkus nya rapi
8,mantap mantap mantap mantap mantap mantap,mantap mantap mantap mantap mantap mantap,mantap mantap mantap mantap mantap mantap,"[mantap, mantap, mantap, mantap, mantap, mantap]","[mantap, mantap, mantap, mantap, mantap, mantap]",mantap mantap mantap mantap mantap mantap
9,"Bagus Banget, Saya akan beli lagi satu lagi","bagus banget, saya akan beli lagi satu lagi",bagus banget saya akan beli lagi satu lagi,"[bagus, banget, saya, akan, beli, lagi, satu, ...","[bagus, banget, beli, satu]",bagus banget beli satu
10,mantap.... paling murah sejagat,mantap.... paling murah sejagat,mantap paling murah sejagat,"[mantap, paling, murah, sejagat]","[mantap, paling, murah, sejagat]",mantap paling murah jagat
11,Kerennnssssss packaging rapi.. Jam nya kece,kerennnssssss packaging rapi.. jam nya kece,kerennnssssss packaging rapi jam nya kece,"[kerennnssssss, packaging, rapi, jam, nya, kece]","[kerennnssssss, packaging, rapi, jam, nya, kece]",kerennnssssss packaging rapi jam nya kece
12,Memang paling cepet deh ini seller ngga sampai...,memang paling cepet deh ini seller ngga sampai...,memang paling cepet deh ini seller ngga sampai...,"[memang, paling, cepet, deh, ini, seller, ngga...","[memang, paling, cepet, deh, seller, ngga, sej...",memang paling cepet deh seller ngga jam recomm...
13,"Topi renangnya bagus, respon seller cepat. TOP...","topi renangnya bagus, respon seller cepat. top...",topi renangnya bagus respon seller cepat top deh,"[topi, renangnya, bagus, respon, seller, cepat...","[topi, renangnya, bagus, respon, seller, cepat...",topi renang bagus respon seller cepat top deh
14,"Belum dicobain yang ini, tapi dari dua yang su...","belum dicobain yang ini, tapi dari dua yang su...",belum dicobain yang ini tapi dari dua yang sud...,"[belum, dicobain, yang, ini, tapi, dari, dua, ...","[dicobain, dicobain, enak]",dicobain dicobain enak
15,"Pesan nya stand gitar, yg dikirim malah stand ...","pesan nya stand gitar, yg dikirim malah stand ...",pesan nya stand gitar yg dikirim malah stand p...,"[pesan, nya, stand, gitar, yg, dikirim, malah,...","[pesan, nya, stand, gitar, yg, dikirim, malah,...",pesan nya stand gitar yg kirim malah stand par...
16,"ok udh sampe, ga bisa di pake du window 10,","ok udh sampe, ga bisa di pake du window 10,",ok udh sampe ga bisa di pake du window 10,"[ok, udh, sampe, ga, bisa, di, pake, du, windo...","[udh, sampe, ga, pake, du, window, 10]",udh sampe ga pake du window 10
17,"Barang telah sampai, sesuai dengan gambar dan ...","barang telah sampai, sesuai dengan gambar dan ...",barang telah sampai sesuai dengan gambar dan d...,"[barang, telah, sampai, sesuai, dengan, gambar...","[barang, sesuai, gambar, diskripsi, semoga, awet]",barang sesuai gambar skripsi moga awet
18,"barang bagus , sayang kurir nya lama kirim jad...","barang bagus , sayang kurir nya lama kirim jad...",barang bagus sayang kurir nya lama kirim jadi ...,"[barang, bagus, sayang, kurir, nya, lama, kiri...","[barang, bagus, sayang, kurir, nya, lama, kiri...",barang bagus sayang kurir nya lama kirim jadi ...
19,"Pengiriman cepat, barang murah, bagus dan be...","pengiriman cepat, barang murah, bagus dan be...",pengiriman cepat barang murah bagus dan berfun...,"[pengiriman, cepat, barang, murah, bagus, dan,...","[pengiriman, cepat, barang, murah, bagus, berf...",kirim cepat barang murah bagus fungsi baik sor...