In [1]:
import pandas as pd
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ACER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [3]:
df = pd.read_csv("../dataset/master.csv")
text_column = "review"

In [6]:
text = "Saya belajar NLP. NLP sangat menarik. Saya ingin menjadi NLP Engineer."

sentences = sent_tokenize(text)

for sentence in sentences:
    print(sentence)

Saya belajar NLP.
NLP sangat menarik.
Saya ingin menjadi NLP Engineer.

In [7]:
from nltk.tokenize import word_tokenize

text = "Saya belajar Natural Language Processing."

tokens = word_tokenize(text)

print(tokens)

['Saya', 'belajar', 'Natural', 'Language', 'Processing', '.']

In [8]:
text = "NLP"

characters = list(text)

print(characters)

['N', 'L', 'P']

In [9]:
df["tokens"] = df[text_column].astype(str).apply(word_tokenize)

df[[text_column, "tokens"]].head()

,review,tokens
0,Kualitas ok\nPelayanan ok,"[Kualitas, ok, Pelayanan, ok]"
1,"kemasan bagus,pengiriman dan respon oke semoga...","[kemasan, bagus, ,, pengiriman, dan, respon, o..."
2,Ok paket sampaii tks gan,"[Ok, paket, sampaii, tks, gan]"
3,"Produk sangat bagus, seller top banget","[Produk, sangat, bagus, ,, seller, top, banget]"
4,.................................................,[................................................

In [10]:
df["jumlah_token"] = df["tokens"].apply(len)
df["jumlah_token"].describe()

count    69975.000000
mean        13.059693
std         14.335847
min          1.000000
25%          6.000000
50%          9.000000
75%         16.000000
max       1155.000000
Name: jumlah_token, dtype: float64

In [11]:
df["jumlah_kata"] = df[text_column].astype(str).apply(
    lambda x: len(x.split())
)

In [12]:
df[["jumlah_kata", "jumlah_token"]].describe()

        jumlah_kata  jumlah_token
count  69975.000000  69975.000000
mean      11.004416     13.059693
std       12.305855     14.335847
min        1.000000      1.000000
25%        5.000000      6.000000
50%        8.000000      9.000000
75%       13.000000     16.000000
max     1036.000000   1155.000000

In [13]:
texts = [
    "Saya suka produk ini.",
    "Bagus banget!!!",
    "Tidak bagus...",
    "Harga Rp50.000.",
    "email@example.com",
    "https://example.com",
    "yg bagus bgt sih",
    "aku udah beli nih kak"
]

for text in texts:
    print("TEXT :", text)
    print("TOKEN:", word_tokenize(text))
    print()

TEXT : Saya suka produk ini.
TOKEN: ['Saya', 'suka', 'produk', 'ini', '.']

TEXT : Bagus banget!!!
TOKEN: ['Bagus', 'banget', '!', '!', '!']

TEXT : Tidak bagus...
TOKEN: ['Tidak', 'bagus', '...']

TEXT : Harga Rp50.000.
TOKEN: ['Harga', 'Rp50.000', '.']

TEXT : email@example.com
TOKEN: ['email', '@', 'example.com']

TEXT : https://example.com
TOKEN: ['https', ':', '//example.com']

TEXT : yg bagus bgt sih
TOKEN: ['yg', 'bagus', 'bgt', 'sih']

TEXT : aku udah beli nih kak
TOKEN: ['aku', 'udah', 'beli', 'nih', 'kak']

In [15]:
import pandas as pd
import nltk
import spacy
from nltk.tokenize import word_tokenize

# Unduh data yang dibutuhkan NLTK (cukup sekali)
nltk.download("punkt", quiet=True)
nltk.download("punkt_tab", quiet=True)

# spaCy multilingual tokenizer tanpa model terlatih
nlp = spacy.blank("xx")

texts = [
    "Saya belajar NLP.",
    "Bagus banget!!!",
    "Harga Rp50.000",
]

hasil = []

for teks in texts:
    hasil.append({
        "Teks": teks,
        "NLTK word_tokenize": word_tokenize(teks, language="english"),
        "split()": teks.split(),
        "spaCy": [token.text for token in nlp(teks)],
    })

tabel_perbandingan = pd.DataFrame(hasil)
display(tabel_perbandingan)

,Teks,NLTK word_tokenize,split(),spaCy
0,Saya belajar NLP.,"[Saya, belajar, NLP, .]","[Saya, belajar, NLP.]","[Saya, belajar, NLP, .]"
1,Bagus banget!!!,"[Bagus, banget, !, !, !]","[Bagus, banget!!!]","[Bagus, banget, !, !, !]"
2,Harga Rp50.000,"[Harga, Rp50.000]","[Harga, Rp50.000]","[Harga, Rp50.000]"